import { sql } from '@/lib/db';
import { notFound } from 'next/navigation';
import styles from './VerifyPage.module.css';

export default async function VerifyPage({ params }: { params: { csn: string } }) {
  const { csn } = params;

  const results = await sql`
    SELECT created_at, verification_hash, sun_sign, nakshatra, life_phase
    FROM reports
    WHERE cosmic_serial_number = ${csn}
    LIMIT 1
  `;

  if (results.length === 0) {
    notFound();
  }

  const record = results[0];

  return (
    <main className={styles.container}>
      <div className={styles.starfield}></div>
      
      <div className={styles.card}>
        <div className={styles.lotus}>🪷</div>
        <h1 className={styles.title}>Origin Point Verified</h1>
        <p className={styles.subtitle}>Immutable Record from the Timestream</p>

        <div className={styles.grid}>
          <div className={styles.item}>
            <span className={styles.label}>Cosmic Serial Number</span>
            <span className={styles.value}>{csn}</span>
          </div>
          <div className={styles.item}>
            <span className={styles.label}>Etched into History</span>
            <span className={styles.value}>{new Date(record.created_at).toLocaleString()}</span>
          </div>
          <div className={styles.item}>
            <span className={styles.label}>Verification Hash (SHA-256)</span>
            <span className={styles.hash}>{record.verification_hash}</span>
          </div>
        </div>

        <div className={styles.divider}></div>

        <div className={styles.signature}>
          <p>This soul-map was generated by Spiritual AI "The Architect" engine.</p>
          <p>It represents an authentic snapshot of a human consciousness pattern.</p>
        </div>

        <div className={styles.footer}>
          <a href="/" className={styles.btn}>Return to the Source</a>
        </div>
      </div>
    </main>
  );
}
