import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@clerk/nextjs/server';
import { prisma } from '@/lib/prisma';
import {
  MBTI_PROFILES,
  PATTERNS,
  PRODUCT_CATALOG,
  recommendProducts,
} from '@/lib/spiritual-conversation-engine';
import {
  createBlock as createBlockPlain,
  assignPlaneX,
  getArchetypeSymbol,
  generateCSNData,
  getNextPlaneY,
} from '@/lib/blockplain';

/**
 * POST /api/blockplain/save
 *
 * The single endpoint that:
 * 1. Authenticates the user (or creates a blockplain user if needed)
 * 2. Generates the Consciousness Identity name
 * 3. Recommends products matched to pattern + MBTI
 * 4. Creates the block in the chain
 * 5. Returns CSN + full report data for the Etching Ceremony
 */
export async function POST(req: NextRequest) {
  try {
    const { userId } = await auth();
    if (!userId) {
      return NextResponse.json({ error: 'Authentication required' }, { status: 401 });
    }

    const body = await req.json();
    const {
      userState,
      // Allow pre-generated report from the spiritual engine
      report: clientReport,
      products: clientProducts,
    } = body;

    if (!userState) {
      return NextResponse.json({ error: 'userState is required' }, { status: 400 });
    }

    // ── Extract key fields ──
    // Validate MBTI: must be a 4-char string from the valid set, not "Undefined", "null", etc.
    const VALID_MBTI_TYPES = new Set([
      'INTJ', 'INTP', 'ENTJ', 'ENTP', 'INFJ', 'INFP', 'ENFJ', 'ENFP',
      'ISTJ', 'ISFJ', 'ESTJ', 'ESFJ', 'ISTP', 'ISFP', 'ESTP', 'ESFP',
    ]);
    const rawMbti = userState.confirmedMBTI || userState.confirmed_mbti || '';
    const mbtiType = (rawMbti && VALID_MBTI_TYPES.has(rawMbti.toUpperCase())) ? rawMbti.toUpperCase() : 'INFP';
    const mbtiProfile = MBTI_PROFILES[mbtiType] || MBTI_PROFILES['INFP'];
    const detectedPattern = userState.detectedPattern || userState.pain_pattern || null;
    const patternData = detectedPattern ? (PATTERNS[detectedPattern] || null) : null;
    const patternName = patternData
      ? patternData.name
      : (detectedPattern || 'unknown')
          .replace(/_/g, ' ')
          .replace(/\b\w/g, (c: string) => c.toUpperCase());
    const archetype = userState.activeArchetype || 'seeker';
    const problem = userState.monetizableProblem || 'Unfulfilled potential';
    const shadow = userState.jungianArchetype || mbtiProfile?.corePattern || 'The Hidden Self';
    const birthDate = userState.birthDate || null;
    const hawkinsLevel = userState.hawkinsLevel || 200;
    const lifeStage = userState.lifeStage || 'The Journey';
    const gender = userState.gender || 'unknown';
    const budget = userState.budget || 'mid';

    // ── Generate the Consciousness Identity name ──
    // This is the 2-3 word title like "The Invisible Architect"
    const consciousnessIdentity = generateConsciousnessIdentity(
      mbtiType,
      archetype,
      patternName,
      shadow
    );

    // ── Build products from catalog ──
    let products: any[] = [];
    if (clientProducts && clientProducts.length > 0) {
      products = clientProducts.slice(0, 3);
    } else {
      try {
        products = recommendProducts(detectedPattern, mbtiType, budget, gender);
      } catch (e) {
        console.error('Product recommendation failed:', e);
      }
    }

    // Ensure 3 products
    const fallbacks = buildFallbackProducts(mbtiType, patternName, detectedPattern);
    for (const fb of fallbacks) {
      if (products.length >= 3) break;
      if (!products.find((p: any) => p.id === fb.id)) products.push(fb);
    }
    products = products.slice(0, 3);

    // ── Build the full report ──
    let report: any;
    if (clientReport && clientReport.header) {
      // Use the report generated by the spiritual engine (Groq)
      report = {
        ...clientReport,
        consciousnessIdentity,
        mbtiType,
        archetype,
      };
    } else {
      // Build report server-side
      report = buildServerReport({
        mbtiType,
        mbtiProfile,
        patternName,
        patternData,
        archetype,
        problem,
        shadow,
        birthDate,
        hawkinsLevel,
        lifeStage,
        consciousnessIdentity,
        userState,
      });
    }

    // ── Ensure user exists in blockplain ──
    let dbUser = await prisma.user.findUnique({ where: { id: userId } });
    if (!dbUser) {
      console.log('Creating new user in database:', userId);
      dbUser = await prisma.user.create({
        data: { id: userId, uid: userId },
      });
    }

    // Assign plane_x if not set
    if (dbUser.plane_x === null) {
      console.log('Assigning plane_x for user:', userId);
      await assignPlaneX(userId);
      dbUser = await prisma.user.findUnique({ where: { id: userId } });
    }

    console.log('User status: active. plane_x:', dbUser?.plane_x);

    // ── Get next plane_y ──
    const plane_y = await getNextPlaneY(userId);
    console.log('Next plane_y for user:', plane_y);

    // ── Create block with a temp CSN first to get the sequence number ──
    const symbol = getArchetypeSymbol(archetype);
    console.log('Creating initial block for user:', userId);
    const tempBlock = await createBlockPlain({
      userId,
      mbti: mbtiType,
      archetype,
      reportData: {}, // placeholder
    });
    console.log('Initial block created. Temp CSN:', tempBlock.csn, 'Sequence:', tempBlock.sequenceNumber);

    // Generate the final CSN with the real sequence number
    const { csn, verifyCode } = await generateCSNData(
      tempBlock.sequenceNumber,
      mbtiType,
      archetype
    );
    console.log('Generated final CSN:', csn);

    // Build identifier snapshot for this blueprint
    const identifierSnapshot: any = {};
    if (mbtiType) identifierSnapshot.mbti = { type: mbtiType, confidence: 0.85, evidence: ['Behavioral inference from conversation'], refinedAt: new Date().toISOString() };
    if (detectedPattern) identifierSnapshot.shadow = { pattern: patternName, confidence: 0.8, evidence: ['Identified during decoding'], refinedAt: new Date().toISOString() };
    if (birthDate) identifierSnapshot.astrology = { sunSign: userState.astrology?.sunSign || 'Unknown', vedicRashi: userState.astrology?.vedicRashi || 'Unknown', nakshatra: userState.astrology?.nakshatra || 'Unknown', confidence: 1.0, refinedAt: new Date().toISOString() };
    if (problem) identifierSnapshot.coreProblem = { problem, confidence: 0.75, evidence: ['Surfaced in conversation'], refinedAt: new Date().toISOString() };
    if (shadow) identifierSnapshot.blindspot = { pattern: shadow, confidence: 0.7, evidence: ['Jungian analysis'], refinedAt: new Date().toISOString() };

    // Build session summary
    const exchangeCount = userState.exchangeHistory?.length || 0;
    const sessionSummary = `${mbtiType} — ${consciousnessIdentity}. Pattern: ${patternName}. Problem: ${problem}. ${exchangeCount} exchanges.`;

    // Update the block with final CSN, report data, identifiers, and summary
    console.log('Updating block with final data...');
    const finalBlock = await prisma.blueprint.update({
      where: { csn: tempBlock.csn },
      data: {
        csn,
        verifyCode,
        plane_y,
        symbol,
        reportData: {
          report,
          products,
          mbtiType,
          patternName,
          archetype,
          symbol,
          consciousnessIdentity,
          gender,
          budget,
          birthDate,
          hawkinsLevel,
          lifeStage,
          problem,
          shadow,
          sequenceNumber: tempBlock.sequenceNumber,
        },
        isComplete: true,
        identifiers: identifierSnapshot,
        summary: sessionSummary,
        conversationDepth: Math.min(100, exchangeCount * 10 + 40),
        engagementScore: userState.interestScore || 50,
      },
    });

    // Also update the UserSummary with the latest blueprint reference
    try {
      await prisma.userSummary.upsert({
        where: { userId },
        create: {
          id: crypto.randomUUID(),
          userId,
          narrative: `${mbtiType} — ${consciousnessIdentity}. Primary struggle: ${patternName}.`,
          identifiers: identifierSnapshot,
          totalSessions: 1,
          lastEngagementScore: userState.interestScore || 50,
          suggestedNextTopic: `Explore a new dimension of "${problem}"`,
          unexploredAreas: ['Career purpose', 'Intimacy patterns', 'Health anxiety', 'Creative blocks', 'Family dynamics'],
          firstBlueprintCsn: csn,
          lastBlueprintCsn: csn,
          problemsExplored: [{ problem, sessionId: 'current', resolved: false, date: new Date().toISOString() }],
        },
        update: {
          narrative: `${mbtiType} — ${consciousnessIdentity}. Primary struggle: ${patternName}.`,
          identifiers: identifierSnapshot,
          lastBlueprintCsn: csn,
          lastRefinedAt: new Date().toISOString(),
        },
      });
    } catch (summaryErr) {
      console.error('Error updating UserSummary on blueprint save:', summaryErr);
      // Non-blocking
    }
    console.log('Block update successful. Final CSN:', finalBlock.csn);

    return NextResponse.json({
      success: true,
      data: {
        csn,
        verifyCode,
        sequenceNumber: finalBlock.sequenceNumber,
        planeX: finalBlock.plane_x,
        planeY: finalBlock.plane_y,
        consciousnessIdentity,
        report,
        products,
        symbol,
        mbti: mbtiType,
        archetype,
        patternName,
      },
    });
  } catch (error: any) {
    console.error('Blockplain save error:', error);
    return NextResponse.json(
      { error: error.message || 'Failed to save blueprint' },
      { status: 500 }
    );
  }
}

// ─── Consciousness Identity Generator ───
// Generates a 2-3 word poetic title like "The Invisible Architect"
function generateConsciousnessIdentity(
  mbti: string,
  archetype: string,
  patternName: string,
  shadow: string
): string {
  const identities: Record<string, string[]> = {
    INFP: ['The Wounded Dreamer', 'The Silent Poet', 'The Hidden Idealist'],
    INFJ: ['The Invisible Oracle', 'The Quiet Prophet', 'The Sacred Martyr'],
    INTJ: ['The Shadow Architect', 'The Frozen Strategist', 'The Lone Sovereign'],
    INTP: ['The Detached Analyst', 'The Paradox Engine', 'The Distant Observer'],
    ENTJ: ['The Iron Commander', 'The Relentless Builder', 'The Wounded King'],
    ENTP: ['The Chaotic Catalyst', 'The Burning Debater', 'The Endless Spark'],
    ENFJ: ['The Radiant Mask', 'The Tired Healer', 'The Silent Guide'],
    ENFP: ['The Scattered Flame', 'The Wounded Optimist', 'The Endless Seeker'],
    ISTJ: ['The Silent Sentinel', 'The Quiet Guardian', 'The Hidden Traditionalist'],
    ISFJ: ['The Invisible Caregiver', 'The Quiet Protector', 'The Tired Giver'],
    ESTJ: ['The Rigid Commander', 'The Unseen Executive', 'The Burdened Leader'],
    ESFJ: ['The Wounded Host', 'The Invisible Diplomat', 'The Tired Harmonizer'],
    ISTP: ['The Detached Mechanic', 'The Quiet Operator', 'The Frozen Virtuoso'],
    ISFP: ['The Wounded Artist', 'The Silent Creator', 'The Hidden Aesthete'],
    ESTP: ['The Restless Actor', 'The Burning Catalyst', 'The Wounded Champion'],
    ESFP: ['The Fading Performer', 'The Wounded Entertainer', 'The Scattered Joy'],
  };

  const options = identities[mbti] || ['The Hidden Self', 'The Unnamed One'];
  // Deterministic based on pattern
  const hash = (patternName + shadow).length % options.length;
  return options[hash];
}

// ─── Build Products (3 layers) ───
function buildFallbackProducts(
  mbti: string,
  patternName: string,
  detectedPattern: string | null
): any[] {
  const p = PRODUCT_CATALOG;
  const items: any[] = [];

  // Always include the consciousness blueprint as the core product
  if (p.consciousness_blueprint) {
    items.push({
      ...p.consciousness_blueprint,
      whyYou: `Built for your ${mbti} architecture carrying "${patternName}".`,
    });
  }

  // Pattern-specific product
  const patternProductId = detectedPattern
    ? (PATTERNS[detectedPattern]?.product || 'shadow_work_journal')
    : 'shadow_work_journal';
  const patternProduct = PRODUCT_CATALOG[patternProductId];
  if (patternProduct && !items.find((i) => i.id === patternProduct.id)) {
    items.push({
      ...patternProduct,
      whyYou: `Designed for the "${patternName}" pattern running through your ${mbti} mind.`,
    });
  }

  // Third product based on MBTI learning style
  const mbtiProfile = MBTI_PROFILES[mbti];
  const thirdProduct =
    mbtiProfile?.designMode === 'study'
      ? p.perfectionism_blueprint
      : mbtiProfile?.designMode === 'action'
        ? p.feeling_body_audio
        : p.boundaries_guide;

  if (thirdProduct && !items.find((i) => i.id === thirdProduct.id)) {
    items.push({
      ...thirdProduct,
      whyYou: `Because as ${mbtiProfile?.name || mbti}, you process through ${mbtiProfile?.learningStyle || 'depth'}.`,
    });
  }

  return items;
}

// ─── Server-side Report Builder ───
function buildServerReport(params: {
  mbtiType: string;
  mbtiProfile: any;
  patternName: string;
  patternData: any;
  archetype: string;
  problem: string;
  shadow: string;
  birthDate: string | null;
  hawkinsLevel: number;
  lifeStage: string;
  consciousnessIdentity: string;
  userState: any;
}) {
  const {
    mbtiType, mbtiProfile, patternName, patternData, archetype,
    problem, shadow, birthDate, hawkinsLevel, lifeStage,
    consciousnessIdentity, userState,
  } = params;

  const exchangeCount = userState.exchangeHistory?.length || 0;
  const userWords = (userState.exchangeHistory || [])
    .filter((e: any) => e.role === 'user')
    .map((e: any) => e.content)
    .join(' ')
    .slice(0, 300);

  return {
    header: {
      architecture: mbtiType,
      patternName,
      urgencyPercent: 75,
      loc: hawkinsLevel,
      csn: 'PENDING', // Will be filled after CSN generation
    },
    consciousnessIdentity,
    mbti: mbtiProfile
      ? {
          name: mbtiProfile.name,
          archetype: mbtiProfile.archetype,
          rarity: mbtiProfile.rarity,
          spiritualPath: mbtiProfile.spiritualPath,
        }
      : null,
    meta: {
      frequencyEstimate: patternData?.runningSince || 'High — this pattern activates daily',
      coreShadowPattern: shadow,
      rootBelief: patternData?.rootCause || 'A decision installed before conscious choice was possible',
      dharmaPhase: lifeStage,
      identifiedProblem: problem,
      exchangeRounds: exchangeCount,
    },
    vedicOverview: birthDate
      ? {
          lagnaAndMoon: `Born ${birthDate}`,
          currentDasha: userState.astrology?.currentMahadasha || 'Active transformation period',
          saturnStatus: 'Growth through discipline',
        }
      : {
          lagnaAndMoon: '[Add birth date to unlock Vedic insights]',
          currentDasha: 'Unknown',
          saturnStatus: 'Unknown',
        },
    validation: patternData
      ? `What you call "${patternName}" is not a flaw. It is a survival mechanism installed in ${patternData.runningSince || 'childhood'} that no longer serves your evolution.`
      : `What you've been experiencing as "${patternName}" is actually a profound pattern — one that Spiritual AI has decoded across thousands of minds before yours.`,
    realCause: patternData?.rootCause
      || 'A pattern installed before conscious choice was possible. Your mind made a decision to survive your environment. That decision became automatic.',
    patternLoop: {
      trigger: 'New opportunity or challenge that threatens the comfort zone',
      copingMechanism: patternData
        ? `The ${patternName} response: familiar, automatic, self-protective`
        : 'Initial excitement followed by avoidance when difficulty arises',
      humanCost: 'Years of unfinished potential and growing self-doubt',
      reset: 'Notice the trigger. Pause. Choose differently — once is enough to begin the break.',
    },
    cosmicConfirmation: patternData?.societyAngle
      || 'The architecture of your mind is not broken — it is specialized. The same mechanism that created this pattern can be redirected toward your evolution.',
    costSection: `The cost of carrying "${patternName}" for another year: approximately ${exchangeCount > 5 ? '400+' : '200+'} hours of lost potential, compounded across every area of your life where this pattern activates.`,
    teaching: mbtiProfile
      ? `As ${mbtiProfile.name} — ${mbtiProfile.archetype}. Your path is ${mbtiProfile.spiritualPath}. The dissolution protocol is: one imperfect action per day for 21 days, calibrated to your ${mbtiProfile.learningStyle} learning style.`
      : 'Your pattern is known. Your path is clear. The first step is awareness — which you now have.',
    witnessQuestion: userState.exchangeHistory?.length > 6
      ? 'If the pattern you decoded today were gone by tomorrow — what would you do differently on Monday morning?'
      : 'What would you do if you knew you could not fail?',
  };
}
