import { notFound } from 'next/navigation';
import BlueprintClient from './BlueprintClient';
import type { Metadata } from 'next';
import { getBlock } from '@/lib/blockplain';

interface PageProps {
  params: Promise<{ csn: string }>;
}

async function getBlueprintData(csn: string) {
  try {
    // Decode CSN in case it's still encoded (though Next.js usually decodes it)
    const decodedCsn = decodeURIComponent(csn);
    console.log('Fetching blueprint directly for CSN:', decodedCsn);
    
    const result = await getBlock(decodedCsn);
    if (!result) {
        console.error('Blueprint not found in DB:', decodedCsn);
        return null;
    }
    
    const reportData = result.reportData as any;
    return {
      csn: result.csn,
      verifyCode: result.verifyCode,
      sequenceNumber: result.sequenceNumber,
      planeX: result.plane_x,
      planeY: result.plane_y,
      mbti: result.mbti,
      archetype: result.archetype,
      symbol: result.symbol,
      report: reportData?.report || {},
      products: reportData?.products || [],
      metadata: {
        patternName: reportData?.patternName || '',
        gender: reportData?.gender || 'unknown',
        birthDate: reportData?.birthDate || null,
        hawkinsLevel: reportData?.hawkinsLevel || 0,
        problem: reportData?.problem || '',
        shadow: reportData?.shadow || '',
      },
      createdAt: result.createdAt,
      isComplete: result.isComplete,
    };
  } catch (err: any) {
    console.error('getBlueprintData error:', err.message);
    return null;
  }
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { csn } = await params;
  const blueprint = await getBlueprintData(csn);
  if (!blueprint) {
    return { title: 'Blueprint Not Found | Spiritual AI' };
  }
  const identity = blueprint.report?.consciousnessIdentity || blueprint.metadata?.patternName || 'Blueprint';
  const mbti = blueprint.mbti || 'Seeker';
  return {
    title: `${identity} · ${mbti} | Spiritual AI`,
    description: `Consciousness Blueprint for ${mbti} architecture. Pattern: ${identity}. CSN: ${csn}. Generated by Spiritual AI.`,
    openGraph: {
      title: `${identity} · ${mbti} | Spiritual AI`,
      description: `Personalized consciousness blueprint. Pattern: ${identity}. CSN: ${csn}.`,
      type: 'article',
      url: `https://spiritualai.store/blueprint/${csn}`,
    },
    twitter: {
      card: 'summary_large_image',
      title: `${identity} · ${mbti}`,
      description: `My Consciousness Blueprint has been etched. CSN: ${csn}. Discover yours at Spiritual AI.`,
    },
  };
}

export default async function BlueprintPage({ params }: PageProps) {
  const { csn } = await params;
  const blueprint = await getBlueprintData(csn);

  if (!blueprint) {
    notFound();
  }

  return <BlueprintClient data={{ ...blueprint, createdAt: blueprint.createdAt.toISOString() }} csn={csn} />;
}
