// Auto-generated by boneyard-js
export const registry = {
  "product-cards": {
    width: 300,
    height: 400,
    items: [
      { type: 'rect', x: 20, y: 20, width: 260, height: 24, radius: 4 },
      { type: 'rect', x: 20, y: 60, width: 100, height: 20, radius: 4 },
      { type: 'rect', x: 20, y: 340, width: 260, height: 40, radius: 4 }
    ]
  }
};
